const colors = {
  light: {
    text: '#1C1C1E',
    tint: '#2D6A4F',
    background: '#F8F4EE',
    foreground: '#1C1C1E',
    card: '#FFFFFF',
    cardForeground: '#1C1C1E',
    primary: '#2D6A4F',
    primaryForeground: '#FFFFFF',
    secondary: '#EDE8E0',
    secondaryForeground: '#3A3A3C',
    muted: '#EDE8E0',
    mutedForeground: '#8E8E93',
    accent: '#C8873F',
    accentForeground: '#FFFFFF',
    destructive: '#FF3B30',
    destructiveForeground: '#FFFFFF',
    border: '#E5DDD4',
    input: '#E5DDD4',
  },
  dark: {
    text: '#F2F2F7',
    tint: '#52B788',
    background: '#1A1A1C',
    foreground: '#F2F2F7',
    card: '#2C2C2E',
    cardForeground: '#F2F2F7',
    primary: '#52B788',
    primaryForeground: '#1A1A1C',
    secondary: '#3A3A3C',
    secondaryForeground: '#E5E5EA',
    muted: '#3A3A3C',
    mutedForeground: '#8E8E93',
    accent: '#E8A35A',
    accentForeground: '#1A1A1C',
    destructive: '#FF453A',
    destructiveForeground: '#F2F2F7',
    border: '#38383A',
    input: '#38383A',
  },
  radius: 12,
};

export default colors;
